@startuml

class MenuItem {
    - key: char {get}
    - text: String {get}
    + MenuItem(key: char, text: String)
}

abstract class Menu {
    # Menu()
    # getTitle(): String {abstract}
    # getDescription(): String {abstract}
    # getMenuItems(): MenuItem[] {abstract}
    # handleMenuSelection(key: char): boolean {abstract}
    + display()
    + prompt(message: String, requireValue: boolean): String {static}
    + prompt(message: String): String {static}
    + delay(milliseconds: long) {static}
}

Menu *-- MenuItem

@enduml